---
title: "BRL_Full_Linking_V3"
author: "Eric Bai"
date: "7/16/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(haven)
library(dplyr)
library(kableExtra)
library(ggplot2)
library(tidyverse)
library(fastLink)
library(RecordLinkage)
library(BRL)
```



```{r}
df1 <- read.csv("C:/DATA/comparison_vectors_V3.csv")
df1$X <- NULL
```


```{r}
#comparisons <- (data.matrix(df))
comparisons <- (df1 == 1)
```

## build full input for bipartite
```{r}
load(file= 'C:/DATA/n1.Rdata')
load(file= 'C:/DATA/n2.Rdata')
nDisagLevs <- c(4, 4, 2, 2)
file1 <- c('fname', 'lname', 'zip', 'age')
file2 <- c('fname', 'lname', 'zip', 'age')
types <- c('lv', 'lv', 'lv', 'lv')

# df
compFields <- data.frame(file1 = file1, file2 = file2, types = types)

res <- list(comparisons = comparisons, n1 = n1, n2 = n2, nDisagLevs = nDisagLevs, compFields = compFields)
```


```{r}
starttime <- Sys.time()
bi <- bipartiteGibbs(res,nIter = 10000)
endtime <- Sys.time()
print(endtime - starttime)
```



```{r}
#saving the 1000 iteration case
#save(bi, file= 'C:/DATA/bi_V3.Rdata')

#saving the 10,000 iteration case
save(bi, file= 'C:/DATA/bi_V3_10k.Rdata')
```



```{r}
#first 100 as burn in bayes estimate
#out <- linkRecords(bi$Z[, -c(1:100)], n1)

##first 1000 as burn in bayes estimate
out <- linkRecords(bi$Z[, -c(1:1000)], n1)
```


```{r}
# save the 900 iterations bayes estimate
#save(out, file= 'C:/DATA/out_V3.Rdata')

# save the 9000 iteration bayes estimate
save(out, file= 'C:/DATA/out_V3_10k.Rdata')

```




```{r}
length(out[out <= n1])/509
```

## create posterior datasets for 10k run

```{r}
#1000 for burn in
out_final <- bi$Z[, -c(1:1000)]
post_data <- out_final
###below is the code for the 100 dataset creation
#col_ind <- seq(1, ncol(out_final),by = 90)
#post_data <- out_final[, col_ind]

```



## simple diag

```{r}

count_match <- function(x){
  num_matches <- sum(x<=n1)
}



num_matches <- apply(post_data, 2, count_match)
mean(num_matches)
```

## save linkage output
```{r}
save(post_data,  file= 'C:/DATA/link_output.Rdata')
```







